remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2
title: HYPER DRIVE

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "HYPER DRIVE on GitHub":
    - "https://github.com/RIVeR-Lab/hyper_drive_data/tree/main"

nav_external_links:
  - title: HYPER DRIVE on GitHub
    url: https://github.com/RIVeR-Lab/hyper_drive_data/tree/main

back_to_top: true
back_to_top_text: "Back to top"
